### ISSUE TITLE
Question about Simulator

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.health#47]
I have a question about the simulator.

What data is being simulated?  and what is the data format of the simulator?
Can the simulator simulate one or more patients?

**Comment by cancilla** [comment]
The simulator generates the 

 - Vitals:
    - HR
    - ABP Systolic
    - ABP Diastolic
    - Temperature
    - SpO2
 - Waveforms
    - ECG Lead I
    - Respiratory

The waveforms are generated at a rate of 125 samples/sec. The vitals are generated at a rate of 10 samples/sec. So for a single patient, the simulator will produce 300 tuples/sec. 

The simulator produces data using the Observation type. The data is output using the PublishConnector, which outputs the Observation type as JSON. By default, the simulator generates data for a single patient, with a patient ID of "patient-1". The simulator can be simulate more than 1 patient. Here is the flow for how this works: 

 1. Generate values for vitals and waveforms for "patient-1"
 2. For each additional patient, duplicate the Observation record and replace the "patient-1" patient ID with another patient ID (i.e. patient-2).
 3. Publish the Observation tuples for all patients

This process allows us to quickly generate data for 10s or 100s of patients while maintaining performance (since we don't need separate threads for each patient). The down-side to this approach is that since the Observation records are all copied, each patient will have the same set of vital and waveform values generated.

**Comment by cancilla** [comment]
I have updated the README.md with the above info. Closing this issue.
